v1.0.1

diff --git a/qbtbar b/qbtbar
--- a/qbtbar
+++ b/qbtbar
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-echo -e "qBittorrent Backup And Restore (QBTBAR) v1.0\n(c) 2024, Alex Free (3-BSD)\n"
+echo -e "qBittorrent Backup And Restore (QBTBAR) v1.0.1\n(c) 2024, Alex Free (3-BSD)\n"
+config="$HOME/.local/share/qBittorrent"
 
 is_running()
 {
@@ -34,13 +35,13 @@ is_installed()
 
 backup_qbt() 
 {
-	if ! [ -d "$HOME/.local/share/qBittorrent" ]; then
-		echo "Error: \""$HOME/.local/share/qBitorrent"\" doesn't exist, so nothing can be backed up."
+	if ! [ -d "$config" ]; then
+		echo "Error: \""$config"\" doesn't exist, so nothing can be backed up."
 		exit 1
 	fi
 
-	if ! [ -d "$HOME/.local/share/qBittorrent/BT_backup" ]; then
-		echo "Error: \"$HOME/.local/share/qBittorrent\" does not contain a \"BT_backup\" directory, so nothing can be backed up."
+	if ! [ -d "$config" ]; then
+		echo "Error: \""$config"\" does not contain a \"BT_backup\" directory, so nothing can be backed up."
 		exit 1
 	fi
 
@@ -76,14 +77,14 @@ restore_qbt()
 		exit 1
 	fi
 
-	if ! [ -d "$HOME/.local/share/qBittorrent" ]; then
-		mkdir -p ~/.local/share/qBittorrent
-		echo "Info: \""$HOME/.local/share/qBitorrent"\" doesn't already exist, so it has been created."
+	if ! [ -d "$config" ]; then
+		mkdir -p "$config"
+		echo "Info: \""$config"\" doesn't already exist, so it has been created."
 	fi
 
 	is_running
 
-	cp -r "$2" ~/.local/share/Qbitorrent
+	cp -r "$2"/* "$config"
 	echo "Backup restored from \"""$2"\".
 }
 
